# Estatísticas de cada tipo por sexo

1. Quantidade de indivíduos em cada combinação de `type` e `sex`
2. Tabela de médias de todas as colunas
3. Estatísticas completas de cada coluna (contagem, média, desvio padrão, mínimo, quartis, mediana e máximo)
4. Exportar para CSV

In [1]:
# Instale uma vez, se precisar: !pip install pandas
import pandas as pd
from IPython.display import display

pd.set_option("display.float_format", lambda x: f"{x:.4f}")

In [2]:
CAMINHO = "abalone_dataset.csv"  # troque pelo caminho do seu arquivo

df = pd.read_csv(CAMINHO)

colunas_numericas = [c for c in df.columns if c not in ["sex", "type"]]
df.head()

,sex,length,diameter,height,whole_weight,shucked_weight,viscera_weight,shell_weight,type
0,M,0.5350,0.4200,0.1500,0.6995,0.2575,0.1530,0.2400,3
1,I,0.5100,0.3800,0.1150,0.5155,0.2150,0.1135,0.1660,1
2,I,0.1850,0.1300,0.0450,0.0290,0.0120,0.0075,0.0095,1
3,M,0.5500,0.4500,0.1700,0.8100,0.3170,0.1570,0.2200,3
4,I,0.5350,0.4150,0.1500,0.5765,0.3595,0.1350,0.2250,1

## 1. Quantidade por tipo e sexo

In [3]:
contagem = pd.crosstab(df["type"], df["sex"], margins=True, margins_name="Total")
contagem

sex      F     I     M  Total
type
1      138   717   223   1078
2      344   214   445   1003
3      471   111   469   1051
Total  953  1042  1137   3132

## 2. Média de cada coluna por tipo e sexo

In [4]:
medias = df.groupby(["type", "sex"])[colunas_numericas].mean()
medias

          length  diameter  height  whole_weight  shucked_weight  \
type sex
1    F    0.5122    0.3974  0.1336        0.7340          0.3339
     I    0.3839    0.2908  0.0948        0.3106          0.1422
     M    0.4757    0.3671  0.1217        0.6244          0.2873
2    F    0.5785    0.4529  0.1537        1.0154          0.4550
     I    0.5126    0.3959  0.1307        0.6385          0.2837
     M    0.5678    0.4439  0.1514        0.9889          0.4504
3    F    0.5966    0.4710  0.1656        1.1457          0.4642
     I    0.5303    0.4122  0.1449        0.7698          0.3203
     M    0.5964    0.4697  0.1646        1.1725          0.4886

          viscera_weight  shell_weight
type sex
1    F            0.1618        0.1990
     I            0.0661        0.0907
     M            0.1354        0.1684
2    F            0.2243        0.2825
     I            0.1357        0.1906
     M            0.2199        0.2689
3    F            0.2520        0.3418
     I            0.1631        0.2344
     M            0.2514        0.3482

## 3. Estatísticas completas de cada coluna

Uma tabela por coluna, com uma linha para cada combinação de `type` e `sex`.

In [5]:
estatisticas = {}

for col in colunas_numericas:
    tabela = df.groupby(["type", "sex"])[col].describe()
    tabela = tabela.rename(columns={"50%": "mediana", "25%": "q1", "75%": "q3"})
    estatisticas[col] = tabela
    print(f"=== {col} ===")
    display(tabela)

=== length ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.5122 0.0875 0.2750 0.4600   0.5250 0.5800 0.7200
     I   717.0000 0.3839 0.0969 0.0750 0.3200   0.3900 0.4550 0.6150
     M   223.0000 0.4757 0.1168 0.1550 0.4150   0.4900 0.5600 0.7200
2    F   344.0000 0.5785 0.0810 0.3300 0.5338   0.5950 0.6350 0.7450
     I   214.0000 0.5126 0.0680 0.2900 0.4750   0.5225 0.5600 0.6800
     M   445.0000 0.5678 0.0873 0.2900 0.5250   0.5850 0.6250 0.7700
3    F   471.0000 0.5966 0.0800 0.3800 0.5400   0.6050 0.6550 0.8150
     I   111.0000 0.5303 0.0720 0.3350 0.4800   0.5300 0.5800 0.6600
     M   469.0000 0.5964 0.0831 0.3100 0.5450   0.6050 0.6500 0.7800

=== diameter ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.3974 0.0706 0.1950 0.3550   0.4075 0.4500 0.5300
     I   717.0000 0.2908 0.0774 0.0550 0.2400   0.2950 0.3500 0.4800
     M   223.0000 0.3671 0.0954 0.1100 0.3100   0.3850 0.4400 0.5650
2    F   344.0000 0.4529 0.0646 0.2600 0.4150   0.4650 0.5000 0.5850
     I   214.0000 0.3959 0.0562 0.2250 0.3612   0.4000 0.4350 0.5300
     M   445.0000 0.4439 0.0707 0.2250 0.4100   0.4600 0.4900 0.6000
3    F   471.0000 0.4710 0.0659 0.3000 0.4250   0.4750 0.5200 0.6500
     I   111.0000 0.4122 0.0581 0.2600 0.3750   0.4150 0.4525 0.5250
     M   469.0000 0.4697 0.0678 0.2350 0.4250   0.4750 0.5150 0.6300

=== height ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.1336 0.0252 0.0700 0.1150   0.1350 0.1500 0.1900
     I   717.0000 0.0948 0.0275 0.0000 0.0800   0.0950 0.1100 0.1850
     M   223.0000 0.1217 0.0323 0.0250 0.1000   0.1250 0.1450 0.2000
2    F   344.0000 0.1537 0.0265 0.0150 0.1400   0.1550 0.1700 0.2250
     I   214.0000 0.1307 0.0193 0.0750 0.1200   0.1300 0.1450 0.1850
     M   445.0000 0.1514 0.0333 0.0650 0.1350   0.1550 0.1700 0.5150
3    F   471.0000 0.1656 0.0291 0.1000 0.1475   0.1650 0.1850 0.2500
     I   111.0000 0.1449 0.0246 0.0900 0.1300   0.1450 0.1600 0.2150
     M   469.0000 0.1646 0.0294 0.0600 0.1450   0.1650 0.1850 0.2500

=== whole_weight ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.7340 0.3150 0.0800 0.4830   0.7522 0.9321 1.4860
     I   717.0000 0.3106 0.1997 0.0020 0.1520   0.2745 0.4420 1.0835
     M   223.0000 0.6244 0.3642 0.0155 0.3523   0.5990 0.8678 1.7100
2    F   344.0000 1.0154 0.3871 0.2000 0.7560   1.0267 1.2636 2.3810
     I   214.0000 0.6385 0.2255 0.1520 0.4714   0.6425 0.7905 1.2975
     M   445.0000 0.9889 0.4046 0.1295 0.7605   1.0040 1.2205 2.3305
3    F   471.0000 1.1457 0.4423 0.2650 0.8160   1.1060 1.4447 2.6570
     I   111.0000 0.7698 0.3072 0.1835 0.5240   0.7405 0.9443 1.7860
     M   469.0000 1.1725 0.4727 0.1200 0.8490   1.1415 1.4605 2.8255

=== shucked_weight ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.3339 0.1520 0.0310 0.2045   0.3265 0.4295 0.7595
     I   717.0000 0.1422 0.0973 0.0010 0.0655   0.1220 0.2015 0.4955
     M   223.0000 0.2873 0.1768 0.0065 0.1515   0.2740 0.4097 0.8255
2    F   344.0000 0.4550 0.1926 0.0625 0.3246   0.4615 0.5719 1.1565
     I   214.0000 0.2837 0.1118 0.0620 0.2096   0.2802 0.3532 0.6035
     M   445.0000 0.4504 0.2029 0.0455 0.3275   0.4565 0.5795 1.2530
3    F   471.0000 0.4642 0.2041 0.1045 0.3013   0.4505 0.5945 1.4880
     I   111.0000 0.3203 0.1423 0.0780 0.2092   0.3045 0.3987 0.7150
     M   469.0000 0.4886 0.2310 0.0415 0.3170   0.4540 0.6325 1.3510

=== viscera_weight ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.1618 0.0708 0.0210 0.1100   0.1645 0.2129 0.3320
     I   717.0000 0.0661 0.0436 0.0005 0.0330   0.0585 0.0925 0.2360
     M   223.0000 0.1354 0.0810 0.0030 0.0770   0.1345 0.1867 0.3855
2    F   344.0000 0.2243 0.0865 0.0370 0.1683   0.2218 0.2807 0.5005
     I   214.0000 0.1357 0.0512 0.0325 0.0998   0.1370 0.1660 0.3220
     M   445.0000 0.2199 0.0941 0.0260 0.1615   0.2195 0.2725 0.5410
3    F   471.0000 0.2520 0.1014 0.0460 0.1720   0.2435 0.3167 0.5900
     I   111.0000 0.1631 0.0676 0.0240 0.1080   0.1605 0.2095 0.3615
     M   469.0000 0.2514 0.1057 0.0330 0.1780   0.2405 0.3080 0.7600

=== shell_weight ===

            count   mean    std    min     q1  mediana     q3    max
type sex
1    F   138.0000 0.1990 0.0846 0.0250 0.1360   0.1885 0.2522 0.4350
     I   717.0000 0.0907 0.0573 0.0015 0.0450   0.0810 0.1250 0.3505
     M   223.0000 0.1684 0.0919 0.0050 0.1030   0.1590 0.2367 0.4325
2    F   344.0000 0.2825 0.1003 0.0700 0.2100   0.2880 0.3442 0.6240
     I   214.0000 0.1906 0.0648 0.0450 0.1465   0.1898 0.2376 0.3860
     M   445.0000 0.2689 0.1021 0.0440 0.2010   0.2725 0.3345 0.5840
3    F   471.0000 0.3418 0.1323 0.0865 0.2500   0.3300 0.4200 1.0050
     I   111.0000 0.2344 0.0866 0.0650 0.1725   0.2235 0.3000 0.4900
     M   469.0000 0.3482 0.1329 0.0400 0.2600   0.3350 0.4300 0.8970

## 4. Exportar para CSV (opcional)

Salva uma tabela única com todas as colunas e estatísticas, para abrir no Excel.

In [6]:
tudo = pd.concat(estatisticas, names=["coluna"]).reset_index()
tudo.to_csv("estatisticas_por_tipo_e_sexo.csv", index=False)
tudo.head()

,coluna,type,sex,count,mean,std,min,q1,mediana,q3,max
0,length,1,F,138.0000,0.5122,0.0875,0.2750,0.4600,0.5250,0.5800,0.7200
1,length,1,I,717.0000,0.3839,0.0969,0.0750,0.3200,0.3900,0.4550,0.6150
2,length,1,M,223.0000,0.4757,0.1168,0.1550,0.4150,0.4900,0.5600,0.7200
3,length,2,F,344.0000,0.5785,0.0810,0.3300,0.5338,0.5950,0.6350,0.7450
4,length,2,I,214.0000,0.5126,0.0680,0.2900,0.4750,0.5225,0.5600,0.6800